#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Host facts land here, not in a project .env. The client reads this file over
# SSH afterwards to write its `factorymac` alias.
mkdir -p "$HOME/.factory"
ENV_FILE="$HOME/.factory/host-info.env"

banner "Factory host setup (Plan 1, Task 1)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Homebrew and Xcode command line tools"
say "Homebrew installs everything else. Xcode CLT supplies git and a compiler."

if command -v brew >/dev/null 2>&1; then
  note "brew already installed: $(brew --version | head -1)"
else
  say "Running the Homebrew installer. It will ask for your Mac password."
  pause "Press Enter to start the installer."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! grep -q 'brew shellenv' "$HOME/.zprofile" 2>/dev/null; then
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME/.zprofile"
  note "added brew to ~/.zprofile"
fi
eval "$(/opt/homebrew/bin/brew shellenv)"

if xcode-select -p >/dev/null 2>&1; then
  note "Xcode command line tools already installed at $(xcode-select -p)"
else
  say "A system dialog will appear. Click Install and wait for it to finish."
  xcode-select --install || true
  pause "Press Enter once the Xcode tools install has completed."
fi

step "Verifying."
brew --version | head -1
git --version
pause "Looks right?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Command line tools"
say "git, gh, node, just, and tmux. The plan pins nothing here, so current is fine."
brew install git gh node just tmux
step "Verifying each one is on PATH."
for t in git gh node just tmux; do
  if command -v "$t" >/dev/null 2>&1; then
    printf '    %s✓%s %-6s %s\n' "$GREEN" "$RESET" "$t" "$(command -v "$t")"
  else
    warn "$t is missing"
    SKIPPED+=("install $t")
  fi
done
pause "All five present?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Docker Desktop and Tailscale (install only)"
say "Installing the two GUI apps now. You sign into them in later stages."
brew install --cask docker || warn "docker cask failed; run 'brew search docker' and record what you find"
brew install --cask tailscale || warn "tailscale cask failed; run 'brew search tailscale' and record what you find"
note "If either cask name has changed upstream, note it and continue; the sign-in stages will tell you."
pause "Press Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Go 1.25.13 for arm64"
say "The fork pins 1.25.13 in .release/go-version and go.mod. Homebrew's Go may"
say "not match, so this uses the official tarball. It will ask for your password."

if command -v go >/dev/null 2>&1 && go version | grep -q 'go1.25.13'; then
  note "already installed: $(go version)"
else
  curl -fsSL -o /tmp/go1.25.13.darwin-arm64.tar.gz \
    https://go.dev/dl/go1.25.13.darwin-arm64.tar.gz
  sudo rm -rf /usr/local/go
  sudo tar -C /usr/local -xzf /tmp/go1.25.13.darwin-arm64.tar.gz
  rm -f /tmp/go1.25.13.darwin-arm64.tar.gz
fi

if ! grep -q '/usr/local/go/bin' "$HOME/.zprofile" 2>/dev/null; then
  echo 'export PATH="$PATH:/usr/local/go/bin"' >> "$HOME/.zprofile"
  note "added Go to ~/.zprofile"
fi
export PATH="$PATH:/usr/local/go/bin"

step "Expected: go version go1.25.13 darwin/arm64"
go version
if go version | grep -q 'go1.25.13 darwin/arm64'; then
  write_env GO_VERSION "$(go version | awk '{print $3}')"
else
  warn "version or architecture does not match the plan. Record this before continuing."
  SKIPPED+=("Go 1.25.13 darwin/arm64, got: $(go version)")
fi
pause "Press Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "GitHub authentication"
say "The worker clones your repositories with this. Factory advertises GitHub"
say "access only while 'gh auth status' succeeds."

if gh auth status --hostname github.com >/dev/null 2>&1; then
  note "already authenticated:"
  gh auth status --hostname github.com 2>&1 | sed 's/^/    /'
else
  step "gh will print a one-time code and open github.com in your browser."
  step "Choose: GitHub.com, HTTPS, and authenticate with a web browser."
  pause "Press Enter to start gh auth login."
  gh auth login
fi

if gh auth status --hostname github.com >/dev/null 2>&1; then
  write_env GH_USER "$(gh api user -q .login)"
else
  warn "gh is still not authenticated"
  SKIPPED+=("gh auth login")
fi
pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Claude Code"
say "This is the only Claude authentication in the whole system. Client devices"
say "never need one, because the agent always runs here."

if command -v claude >/dev/null 2>&1; then
  note "already installed: $(claude --version 2>/dev/null || echo 'version unknown')"
else
  npm install -g @anthropic-ai/claude-code
fi

# Claude Code's native installer lands in ~/.local/bin and adds its PATH line
# to .zshrc, which only interactive shells read. The worker spawns the agent
# from a login shell under tmux, so the entry has to be in .zprofile too.
if ! grep -q '\.local/bin' "$HOME/.zprofile" 2>/dev/null; then
  printf 'export PATH="$HOME/.local/bin:$PATH"\n' >> "$HOME/.zprofile"
  note "added ~/.local/bin to ~/.zprofile so login shells find claude"
fi
export PATH="$HOME/.local/bin:$PATH"

step "Launching Claude Code. Complete the browser login, then type /exit."
pause "Press Enter to launch it."
claude || true

step "Expected: a version string, with no authentication prompt."
if claude --version >/dev/null 2>&1; then
  write_env CLAUDE_VERSION "$(claude --version 2>&1 | head -1)"
else
  warn "claude --version failed"
  SKIPPED+=("Claude Code authentication")
fi
pause "Press Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Docker Desktop first run"
say "Plan 4 adds a Docker sandbox backend. Task 9 preflights it. Both need the"
say "daemon running, and the first launch has prompts only you can accept."

open -a Docker 2>/dev/null || warn "could not launch Docker Desktop; open it from Applications"
step "Accept the licence and the privileged helper prompt if they appear."
pause "Press Enter once Docker Desktop shows as running."

# The daemon can take a while after first launch, and it is easy to press
# Enter before it is ready. Wait rather than failing on the first miss.
DOCKER_OK=0
for _ in $(seq 1 30); do
  if docker info >/dev/null 2>&1; then DOCKER_OK=1; break; fi
  printf '    %swaiting for the docker daemon...%s\r' "$DIM" "$RESET"
  sleep 2
done
printf '\033[2K'
if [[ "$DOCKER_OK" == "1" ]]; then
  printf '    %s✓%s docker ok\n' "$GREEN" "$RESET"
  write_env DOCKER_VERSION "$(docker --version)"
else
  warn "docker info failed after 60s. Task 9 will be blocked until this works."
  SKIPPED+=("Docker daemon running")
fi
pause "Press Enter to continue."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Tailscale sign-in"
say "The tailnet is this system's trust boundary. Nothing binds a public"
say "interface; the cockpit is reached through 'tailscale serve'."

TS=""
if command -v tailscale >/dev/null 2>&1; then
  TS="tailscale"
elif [[ -x /Applications/Tailscale.app/Contents/MacOS/Tailscale ]]; then
  TS="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
  if confirm "Symlink the tailscale CLI into /opt/homebrew/bin so it is on PATH?"; then
    sudo ln -sf "$TS" /opt/homebrew/bin/tailscale && TS="tailscale"
  fi
fi

if [[ -n "$TS" ]] && "$TS" ip -4 >/dev/null 2>&1; then
  note "already signed in to a tailnet; nothing to do here"
else
  open -a Tailscale 2>/dev/null || warn "could not launch Tailscale; open it from Applications"
  step "Sign in to your tailnet from the Tailscale menu bar icon."
  pause "Press Enter once this Mac shows as connected."
fi

if [[ -n "$TS" ]]; then
  "$TS" status 2>&1 | head -5 | sed 's/^/    /'
  TS_IP=$("$TS" ip -4 2>/dev/null | head -1 || true)
  TS_DNS=$("$TS" status --json 2>/dev/null \
    | python3 -c 'import json,sys;print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || true)
else
  warn "could not find the tailscale CLI"
  TS_IP=""; TS_DNS=""
fi

if [[ -z "$TS_DNS" ]]; then
  step "Read the machine's full name from the Tailscale admin console."
  open_url "https://login.tailscale.com/admin/machines"
  ask TAILNET_DNS "Paste this Mac's tailnet DNS name (e.g. macmini.tailXXXX.ts.net):"
else
  TAILNET_DNS="$TS_DNS"
  note "detected tailnet DNS name: $TAILNET_DNS"
fi
if [[ -z "$TS_IP" ]]; then
  ask TAILNET_IP "Paste this Mac's tailnet IPv4 address:"
else
  TAILNET_IP="$TS_IP"
  note "detected tailnet IPv4: $TAILNET_IP"
fi

write_env TAILNET_DNS "$TAILNET_DNS"
write_env TAILNET_IP "$TAILNET_IP"
pause "Press Enter to continue."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Prevent sleep"
say "A sleeping host stalls runs and drops your orchestrator session."
if pmset -g | grep -qE '^[[:space:]]*sleep[[:space:]]+0'; then
  note "sleep is already prevented; no change needed"
else
  say "This sets sleep to 0 on power. It will ask for your password."
  sudo pmset -a sleep 0 || warn "pmset failed; set it in System Settings, Energy"
fi

step "Expected: sleep 0"
pmset -g | grep -E '^[[:space:]]*sleep' | sed 's/^/    /' || warn "could not read pmset"
if pmset -g | grep -qE '^[[:space:]]*sleep[[:space:]]+0'; then
  printf '    %s✓%s host will not sleep on power\n' "$GREEN" "$RESET"
else
  SKIPPED+=("prevent sleep via System Settings, Energy")
fi
pause "Press Enter to continue."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Remote access readiness and host record"
say "Confirming this Mac is ready for SSH clients and VS Code Remote-SSH."

if launchctl list 2>/dev/null | grep -q 'com.openssh.sshd' || sudo systemsetup -getremotelogin 2>/dev/null | grep -qi 'on'; then
  printf '    %s✓%s Remote Login is on\n' "$GREEN" "$RESET"
else
  warn "Remote Login looks off. System Settings, General, Sharing, Remote Login."
  SKIPPED+=("enable Remote Login")
fi

if [[ -s "$HOME/.ssh/authorized_keys" ]]; then
  printf '    %s✓%s %s client key(s) authorised\n' "$GREEN" "$RESET" "$(grep -c '^ssh-' "$HOME/.ssh/authorized_keys" || echo 0)"
else
  warn "no authorized_keys yet. Run ssh-copy-id from your client before leaving the Mac."
  SKIPPED+=("ssh-copy-id from the client")
fi

note "VS Code Remote-SSH needs nothing installed here; it downloads its own"
note "server into ~/.vscode-server on first connect. Only Remote Login matters."

write_env MAC_USER "$(whoami)"
write_env MAC_HOSTNAME "$(scutil --get LocalHostName 2>/dev/null || hostname)"
write_env MAC_ARCH "$(uname -m)"
write_env MACOS_VERSION "$(sw_vers -productVersion)"

finish

printf '  %sHost record written to%s %s\n\n' "$BOLD" "$RESET" "$ENV_FILE"
cat "$ENV_FILE" | sed 's/^/    /'
printf '\n  %sNext:%s from your client, run\n' "$BOLD" "$RESET"
printf '    ssh %s@%s "uname -m && go version"\n\n' "$(whoami)" "${TAILNET_DNS:-<tailnet-dns-name>}"
