package web

import (
	"embed"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

// dist is generated by `npm run build` and committed so every factory-server
// binary contains the same reviewed production UI without needing Node at run time.
//
//go:embed dist
var assets embed.FS

type handler struct {
	api   http.Handler
	files http.Handler
	dist  fs.FS
	index []byte
}

// NewHandler serves the same-origin control-plane API and embedded React app.
// Client-side routes fall back to index.html, while missing asset requests stay
// honest 404s instead of returning HTML to a script or stylesheet request.
func NewHandler(api http.Handler) http.Handler {
	dist, err := fs.Sub(assets, "dist")
	if err != nil {
		panic("open embedded UI: " + err.Error())
	}
	index, err := fs.ReadFile(dist, "index.html")
	if err != nil {
		panic("read embedded UI index: " + err.Error())
	}
	return &handler{
		api:   api,
		files: http.FileServer(http.FS(dist)),
		dist:  dist,
		index: index,
	}
}

func (h *handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/healthz" || strings.HasPrefix(r.URL.Path, "/api/") {
		h.api.ServeHTTP(w, r)
		return
	}
	setBrowserHeaders(w)
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		w.Header().Set("Allow", "GET, HEAD")
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	name := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
	if name == "." || name == "" {
		h.serveIndex(w, r)
		return
	}
	if info, err := fs.Stat(h.dist, name); err == nil && !info.IsDir() {
		if strings.HasPrefix(name, "assets/") {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		}
		h.files.ServeHTTP(w, r)
		return
	}
	if path.Ext(name) != "" {
		http.NotFound(w, r)
		return
	}
	h.serveIndex(w, r)
}

func (h *handler) serveIndex(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Del("Content-Length")
	if r.Method == http.MethodGet {
		_, _ = w.Write(h.index)
	}
}

func setBrowserHeaders(w http.ResponseWriter) {
	w.Header().Set("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'")
	w.Header().Set("Referrer-Policy", "no-referrer")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("X-Frame-Options", "DENY")
}
